### ISSUE TITLE
RadSideDrawer - ui/core/view.CustomLayoutView undefined

### ISSUE THREAD

**Issue by Farbdose** [telerik/nativescript-ui-samples#119]
### Steps to reproduce: 
Download [SampleProject](https://dl.dropboxusercontent.com/u/21322609/GitIssue.zip)
run `tns platform add android` and `tns run android`

### The Problem
Trying to get RadSideDrawer working:
No matter what I do, as soon as I use `@ViewChild` I get a:

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

TypeError: Cannot read property 'extend' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'__extends', file:'/data/data/org.nativescript.EZPZEventEpp/files/internal/ts_helpers.js', line: 47, column: 13
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/content-view/content-view.js', line: 4, column: 5
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/content-view/content-view.js', line: 85, column: 2
Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/page/page-common.js', line: 1, column: 82
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/page/page.js', line: 1, column: 78
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/frame/frame-common.js', line: 2, column: 14
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/frame/frame.js', line: 1, column: 79
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/application/application-common.js', line: 3, column: 13
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/application/application.js', line: 1, column: 77
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/styling/style.js', line: 1, column: 79
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/core/view-common.js', line: 2, column: 13
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/core/view.js', line: 1, column: 78
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/core/bindable.js', line: 7, column: 18
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/ui/core/proxy.js', line: 1, column: 76
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/nativescript-telerik-ui-pro/sidedrawer/sidedrawer-common.js', line: 2, column: 13
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/nativescript-telerik-ui-pro/sidedrawer/sidedrawer.js', line: 1, column: 74
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/tns_modules/nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives.js', line: 2, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/app.component.js', line: 4, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.EZPZEventEpp/files/app/main.js', line: 7, column: 23
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4809)
	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 
Error calling module function 

```
I poked around in the `ui/core/view` and found out, that for some reason `View.CustomLayoutView` is undefined. Which is ridiculous ... 
I already tried to reinstall most of the modules in case something got damaged (removed and added android platform again too) - without success.
Hopefully someone sees an obvious mistake in my code that explains it all :-/ 

### app.component.ts:

```
import {SharedService} from "./shared/index";
import { Component, ElementRef, ViewChild, Inject, OnInit, ChangeDetectorRef } from "@angular/core";
import { View } from "ui/core/view";
import { RadSideDrawer } from "nativescript-telerik-ui-pro/sidedrawer";
import { ActionItem } from "ui/action-bar";
import 'nativescript-telerik-ui-pro/sidedrawer/angular';
import * as ObservableModule from "data/observable";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui-pro/sidedrawer/angular";
import { Router }     from '@angular/router';

@Component({
    selector: "main",
    directives:
        [SharedService.GET_ROUTER_DIRECTIVES()],
    styleUrls:["./app.component.css"],
    templateUrl: "./app.component.html"
})
export class AppComponent extends ObservableModule.Observable implements OnInit {

    constructor(
        private _changeDetectionRef: ChangeDetectorRef,
        private router: Router) {
        super();
    }


    @ViewChild("drawer") public drawerComponent: RadSideDrawerComponent;
    private drawer: SideDrawerType;


    ngAfterViewInit() {
        this.drawer = this.drawerComponent.sideDrawer;
        this._changeDetectionRef.detectChanges();
    }

    ngOnInit() {
        //this.set("mainContentText", "SideDrawer for NativeScript can be easily setup in the XML definition of your page by defining main- and drawer-content. The component"
        //    + " has a default transition and position and also exposes notifications related to changes in its state. Swipe from left to open side drawer.");
    }

    public openDrawer() {
        this.drawer.showDrawer();
    }

    public moveTo(target:String){
        this.router.navigate([target]);
    }
}
```

### app.component.html:
```
<RadSideDrawer #drawer>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label (tap)="moveTo('/')" text="StartScreen" class="sideLabel"></Label>
            <Label (tap)="moveTo('/dummy')" text="Dummy" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
        <Button (tap)="openDrawer()" text="Open Drawer"></Button>
        <page-router-outlet></page-router-outlet>
    </StackLayout>
</RadSideDrawer>
```

### main.ts:

```
import { SharedService } from "./shared/index"
SharedService.IS_NATIVESCRIPT() && require(""+"reflect-metadata");

import { provide, PLATFORM_DIRECTIVES } from '@angular/core';
import { NATIVESCRIPT_WEB_COMPONENTS} from './native-web-components/index';
import { AppComponent } from "./app.component";
import { APP_ROUTER_PROVIDERS } from "./app.routes";

let bootstrap = SharedService.GET_BOOTSTRAP();
let providers = [SharedService.GET_HTTP_PROVIDER(), APP_ROUTER_PROVIDERS].concat([SharedService.IS_NATIVESCRIPT() ?
    SharedService.GET_SIDEDRAWER_PROVIDERS():
    provide(PLATFORM_DIRECTIVES, {useValue: NATIVESCRIPT_WEB_COMPONENTS, multi: true})]);

bootstrap(AppComponent, providers);
```

**Comment by VladimirAmiorkov** [comment]
Hi @Farbdose ,

I see that the provided sample project is using the RC4 version of Angular 2, since the official version has been released it introduced couple of braking changes which have been resolved additionally much of the bootstrapping has changed making this sample project obsolete.  I tested the "[SideDrawer: Getting Started](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/sidedrawer/getting-started)" example from the repository and no exception were observed. 

Could you give it a try and let me know if you continue to experience the mentioned issue.

**Comment by VladimirAmiorkov** [comment]
Hi @Farbdose ,

I see that the provided sample project is using the RC4 version of Angular 2, since the official version has been released it introduced couple of braking changes which have been resolved additionally much of the bootstrapping has changed making this sample project obsolete.  I tested the "[SideDrawer: Getting Started](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/sidedrawer/getting-started)" example from the repository and no exception were observed. 

Could you give it a try and let me know if you continue to experience the mentioned issue. Closing the issue for now, feel free to reopen it if you experience this error again.
