### ISSUE TITLE
After installing 0.0.8, App crashes on startup on specific device

### ISSUE THREAD

**Issue by lscown** [telerik/nativescript-ui-samples#17]
Hey there,

So after installing 0.0.8, it worked perfectly fine on a few Android devices and emulators (including nexus 5, API 22 emulator). However, as soon as it runs on my own Nexus 5, 5.1.1 it crashes. I downgraded to 0.0.4 and it worked again. 

This is the stack trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.mobile/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
NativeScript application not initialized correctly. getActivity method returned invalid value.

Error: A Frame must be used to navigate to a Page.
File: "/data/data/com.app.mobile/files/app/tns_modules/application/application.js, line: 129, column: 22

StackTrace: 
  Frame: function:'AndroidApplication.getActivity', file:'/data/data/com.app.mobile/files/app/tns_modules/application/application.js', line: 129, column: 23
  Frame: function:'app.init.getActivity', file:'/data/data/com.app.mobile/files/app/tns_modules/application/application.js', line: 104, column: 32


  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
  at android.app.ActivityThread.access$800(ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5254)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: com.tns.NativeScriptException: 
NativeScript application not initialized correctly. getActivity method returned invalid value.

Error: A Frame must be used to navigate to a Page.
File: "/data/data/com.app.mobile/files/app/tns_modules/application/application.js, line: 129, column: 22

StackTrace: 
  Frame: function:'AndroidApplication.getActivity', file:'/data/data/com.app.mobile/files/app/tns_modules/application/application.js', line: 129, column: 23
  Frame: function:'app.init.getActivity', file:'/data/data/com.app.mobile/files/app/tns_modules/application/application.js', line: 104, column: 32


  at com.tns.NativeScriptActivity.getMethodOverrides(Native Method)
  at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:1567)
  at android.app.Activity.performCreate(Activity.java:5990)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
  ... 10 more
```

**Comment by lscown** [comment]
Can confirm that <= 0.07 works fine

**Comment by ginev** [comment]
Hi lscown,

We're looking into this issue and will get back to you later today with more information.

Stay tuned.

**Comment by ginev** [comment]
Hi @lscown,

Can you please share more information on the version of NativeScript you are using?
This exception might occur when you have incompatible versions of the NS runtime and the core modules.

Can you try creating a brand new NS application, pasting your application code there (without tns_modules folder) and installing the Telerik UI plugin? Does this work as expected?

Thanks for your time!

**Comment by krishnasripada** [comment]
I had the same issue and I got it fixed by editing my Javascript. I forgot the start the application from the app.js file that lead me to this error. Hope this fixes your issue as well!
